---
title: "Ellemberg values"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE, error = FALSE)
library(leaflet)
library(tidyverse)
library(htmltools)
library(bsplus)
library(vegan)
library(crosstalk)
library(sf)
library(DT)
library(plotly)

Test <- read_rds("/home/derek/Documents/Site_Selection_DK/AllData4.rds") %>% 
  dplyr::filter(Dataset == "Novana") %>% 
  separate(col = "ID", into = c("ID", "plot"))

saveRDS(Test, "Spatial.rds")
```


```{r cars, cache=TRUE, include=FALSE}
Artlist <- data.table::fread("artsliste.csv") %>%
  as.data.frame() 

library(readr)

frekvens2 <- read_csv("alledata-frekvens2.txt") %>%
  janitor::clean_names() %>%
  as_tibble()

frekvens2$species <- str_split(frekvens2$specieslist, ",")

frekvens2 <- frekvens2 %>%
    dplyr::select(-specieslist) %>%
    unnest(species) %>%
    mutate(species = str_trim(species, side = "both"),
           species = str_remove_all(species, "\\}"),
           site = str_remove_all(site, "\\{"),
           species = as.numeric(species)) %>%
    rename(ArtID = species) %>%
    left_join(Artlist) %>% 
    mutate(plot = as.character(plot)) %>% dplyr::select(plot, year, LatArt) %>% 
  dplyr::filter(year < (lubridate::year(lubridate::ymd(Sys.Date())) + 1)) %>% 
  group_by(plot) %>% 
  dplyr::filter(year == max(year))  %>% 
  dplyr::filter(LatArt != "") 
#  left_join(Test)

PlotRichness <- frekvens2 %>% ungroup() %>% 
  group_by(plot) %>% 
  summarise(Richness = n())

#saveRDS(PlotRichness, "PlotRichness.rds")

PlotCommunity <- frekvens2 %>% 
  ungroup() %>% 
  mutate(Pres = 1) %>% 
  dplyr::distinct() %>% 
  dplyr::filter(LatArt != "") %>% 
  pivot_wider(names_from = LatArt, values_from = Pres, values_fill = 0) %>% 
  janitor::clean_names()

saveRDS(PlotCommunity, "PlotCommunity.rds")

PlotSppList <- frekvens2 %>% 
  ungroup() %>% 
  nest(Species = LatArt)

set.seed(2021)
PlotSppNames <- frekvens2 %>% 
    ungroup() %>% 
    group_by(plot) %>% 
#    summarise(Species = paste(LatArt, collapse = "<br/> "), n = paste("Number of species", n())) 
  summarise(Species = paste(LatArt, collapse = ", "), n = paste("Number of species", n()), Richness = n()) %>% 
  filter(complete.cases(.)) %>% 
  slice_sample(n = 1000)

Final <- list()

for(i in 1:nrow(PlotSppNames)){
  Button <- bs_button(PlotSppNames$n[i], button_type = "primary") %>% bs_attach_collapse(paste0("id_spp", i))
SppList = bs_collapse(id = paste0("id_spp", i), PlotSppNames$Species[i])

Final[[i]] = paste(sep = "<br/>", Button, SppList)
}

Final <- Final %>% purrr::reduce(c)

PlotSppNames$Species <- Final
```


```{r Table}

NMDS <- readRDS("NMDSplots.rds")

result <- Test %>% 
  right_join(PlotSppNames) %>% dplyr::select(plot, Species, MajorHab, Richness) %>% 
  right_join(NMDS) %>% 
  st_transform("+proj=longlat +datum=WGS84") %>% 
  dplyr::distinct() %>% 
  dplyr::select(-year, -CheckPoint)

PlotSppList <- PlotSppList %>% dplyr::filter(plot %in% result$plot)

pal <- colorFactor(palette = c("#F8766D", "#A3A500", "#00BF7D", "#00B0F6", "#E76BF3"), domain = c("A", "B", "C", "D", "E"))

saveRDS(PlotSppList, "TestSppList.rds")

#leaflet(result) %>% addTiles() %>% 
#  addMarkers(popup = PlotSppNames$Species)

#DT::datatable(result, escape = F)

sd <- SharedData$new(result)

# Create a filter input
bscols(list(
filter_slider("Richness", "Species Richness", sd, column=~Richness, step=1, width=250),
filter_checkbox("Class", "Class", sd, ~Class, inline = TRUE),
filter_checkbox("Major Habitar", "MajorHab", sd, ~MajorHab, inline = T)
))
# Use SharedData like a dataframe with Crosstalk-enabled widgets
bscols(
  leaflet(sd) %>% addTiles() %>% addCircleMarkers(popup = ~Species, color = ~pal(Class)),
  ggplotly(ggplot(sd, aes(x = PC1, y = PC2)) + geom_point(aes(color = Class)) + theme_bw())
)

DT::datatable(sd, escape = F, extensions = c('Buttons', 'Scroller'), width="100%",
    options=list(scrollY=300, scroller=TRUE, buttons = c('copy', 'csv', 'excel')),fillContainer = T) %>%
    formatRound(columns=c("L", "T", "K", "F", "R", "N", "S", "MDS1", "MDS2", "PC1", "PC2", "PC3"), digits=2)

```

